### PR TITLE
Adjust_movie_regex

### PR DESCRIPTION
**Pull request by williamrowell**
The previous movie regex matched either upgrade (`U`) or IIe (`e`) instruments.  The regex has been upgraded to match upgraded `Ue` instruments as well.

### CODE REVIEW

**Comment by amwenger** [comment]
Looks good to me.

What do you think if we significantly relax the matching requirement to something like `(?P<movie>[A-Za-z0-9_]*).(ccs|hifi_reads).bam`?

**Comment by williamrowell** [comment]
What is the purpose of relaxing the regex?  Is it to handle filenames from demuxed movies?

**Comment by amwenger** [comment]
> What is the purpose of relaxing the regex? Is it to handle filenames from demuxed movies?
Purpose is to be more general since we do not rely on the movie part of the regex match.  We need hifi_reads.bam or ccs.bam to know how to handle the file (compared to fastq), but not movie part.

I am fine with the more stringent regex too but do not think it is necessary.

**Comment by williamrowell** [comment]
My argument for keeping the current regex is that by matching the output of SMRT Link, we indicate what types of files are intended as input.

Also, allowing for a less stringent regex could get us into trouble downstream, if the `movie` component contains substrings that match fixed path components downstream.

**Comment by amwenger** [comment]
Good point.  Then I think this is good to merge as-is.

**Pull request merged**
