### PR TITLE
update snakemake profiles

### LINKED ISSUE #90: Memory is not properly provided for cluster execution
Our Slurm cluster enforces memory usage with cgroups. I added `--mem=32G` as a default to the snakemake profile. This is of course not good enough as it is too high for certain steps and too low for the assembly. If I increase it for assembly then the number of jobs running in parallel is too low.

The resolution would be to set proper memory resources for all rules.

### PR DESCRIPTION
**Pull request by juniper-lake**
Added default memory per cpu/thread and max-threads (which puts a cap on all rule-specific threads). 

Resolves #90

### CODE REVIEW

**Review by williamrowell — APPROVED** [review]
Looks good to me. Is there a way to log what resources were requested when the job was submitted so we can be sure this is doing what we expected?

**Comment by juniper-lake** [comment]
If the "message" section of each rule is removed then the default output in the snakemake log file includes a list of all resources and wildcards. Default resources stemming from variables.env just display as the environment variable (i.e. $PARTITION and $ACCOUNT) but i tested that $PARTITION gets expanded properly and the correct $ACCOUNT is required for singularity to work I believe.

**Comment by williamrowell** [comment]
> If the "message" section of each rule is removed then the default output in the snakemake log file includes a list of all resources and wildcards. Default resources stemming from variables.env just display as the environment variable (i.e. $PARTITION and $ACCOUNT) but i tested that $PARTITION gets expanded properly and the correct $ACCOUNT is required for singularity to work I believe.

The `message` directives aren't really useful.  Do we want to get rid of them?

**Comment by juniper-lake** [comment]
Yeah, that makes sense. In this PR or a different one?

**Pull request merged**
