### PR TITLE
Cleanup intermediate files that aren't explicit targets

### PR DESCRIPTION
**Pull request by williamrowell**
(Related to #3)

These untested changes should cleanup intermediate files from DeepVariant, WhatsHap, and pbsv:
- first pass VCFs and phased VCFs and indices
- split per-chromosome VCFs and indices
- first pass haplotagged BAMs and indices

There may still be some empty folders left over, but larger files should be gone.

What do you think about removing per-movie aligned BAMs as well?

### CODE REVIEW

**Comment by amwenger** [comment]
I like these changes.  In addition to saving space, it reduces confusion about which files are final targets.  Should we also add the second-pass DeepVariant VCF since the WhatsHap phased VCF is the final target?

> What do you think about removing per-movie aligned BAMs as well?
Removing them would be great.  How would you apply that - an explicit delete stage at the end of process_sample?  To avoid triggering re-work in process_smrtcells, perhaps we could set the bam.md5 files as the target for process_smrtcells and keep the md5 files around?

**Comment by williamrowell** [comment]
> Should we also add the second-pass DeepVariant VCF since the WhatsHap phased VCF is the final target?

Not sure exactly what you're asking for here.  Do you want the second-pass DeepVariant VCF to be deleted, or to be retained?

> Removing them would be great. How would you apply that - an explicit delete stage at the end of process_sample?

I forgot that they're created in a separate snakemake.  I guess we're stuck manually deleting them, unless we want to make a special rule that checks for all of the downstream analyses before deleting them and leaving a flag file.

**Comment by amwenger** [comment]
> Not sure exactly what you're asking for here. Do you want the second-pass DeepVariant VCF to be deleted, or to be retained?

I meant deleted.

> I forgot that they're created in a separate snakemake. I guess we're stuck manually deleting them, unless we want to make a special rule that checks for all of the downstream analyses before deleting them and leaving a flag file.

I think it's worthwhile to delete them.  We could add a rule to delete the BAM and create a BAM.deleted flag file with two inputs: the SMRT Cell BAMs and the first WhatsHap-phased BAM (or any other direct outputs of the per-SMRT Cell BAM).

**Comment by williamrowell** [comment]
The problem is that `process_smrtcells` would recreate them the next time it runs on cron.

**Comment by amwenger** [comment]
> `process_smrtcells` would recreate them the next time it runs on cron
I think we could avoid that if the targets for `process_smrtcells` were something downstream of the aBAM, like the aBAM.md5 or the smrtcell stats.  Then, if we keep the `aBAM.md5` when deleting the `aBAM`, then process_smrtcells would not re-run (or at least I think).

> Also, they are used by `process_cohort` to phase small variants in multi-sample cohorts.
That sounds like a good enough reason to keep the SMRT Cell aBAMs unless it is not simple to make `process_cohort` take the "final" phased aBAM from `process_sample`.

**Comment by williamrowell** [comment]
Currently stalled by https://github.com/snakemake/snakemake/issues/1271.

**Comment by williamrowell** [comment]
What do you think about the options outlined in https://github.com/snakemake/snakemake/issues/1271#issuecomment-1000403199?

- add 'cleanup' rules to specifically delete intermediate files
- move final output to another folder

**Comment by amwenger** [comment]
Neither sounds great to me; so, my leaning is to stay with what we have (i.e. just let the files stick around).  What do you think?

**Comment by williamrowell** [comment]
I agree.  Neither solution really sounds great.  The 'cleanup' rules sound marginally better, but they will, by necessity, leave behind flag files that could be confusing to an end user.

**Comment by williamrowell** [comment]
Closing this for now until we can come up with a better solution to clean up intermediate files.

**Pull request closed without merging**
